[package]
name = "ec-divisors-contest"
version = "0.1.0"
edition = "2021"

[dependencies]
ec-divisors = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", version = "0.1", features = ["ed25519"] }

dalek-ff-group = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", default-features = false, optional = true }
pasta_curves = { version = "0.5", git = "https://github.com/kayabaNerve/pasta_curves.git", default-features = false, features = ["bits", "alloc"], optional = true }
std-shims = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", version = "^0.1.1", default-features = false }

ff = { version = "0.13", default-features = false, features = ["bits"] }
group = { version = "0.13", default-features = false }
hex = { version = "0.4", default-features = false, optional = true }
subtle = { version = "2", default-features = false }
zeroize = { version = "^1.5", default-features = false, features = ["zeroize_derive"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
hex = "0.4"
rand_core = { version = "0.6", features = ["getrandom"] }

ciphersuite = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", version = "0.4", features = ["ed25519"] }
dalek-ff-group = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", features = ["std"] }
pasta_curves = { version = "0.5", git = "https://github.com/kayabaNerve/pasta_curves.git", default-features = false, features = ["bits", "alloc"] }

[features]
std = ["std-shims/std", "zeroize/std", "subtle/std", "ff/std", "dalek-ff-group?/std"]
ed25519 = ["hex/alloc", "dalek-ff-group"]
pasta = ["pasta_curves"]
default = ["std"]

[[bench]]
name = "divisors"
harness = false
required-features = ["ed25519"]
